ci: rollback the waiting action - ensure  finished previous workflow isn´t otherwise possible

diff --git a/.github/workflows/docker-publish_dev.yml b/.github/workflows/docker-publish_dev.yml
--- a/.github/workflows/docker-publish_dev.yml
+++ b/.github/workflows/docker-publish_dev.yml
@@ -53,6 +53,43 @@ jobs:
       packages: write
 
     steps:
+      - name: Get the run_id of the most recent run workflow
+        id: get_run_id
+        run: |
+          # Use the GitHub API to get the latest run_id of the first workflow
+          run_id=$(curl -s -H "Authorization: token ${{ secrets.GH_PACKAGE_TOKEN }}" \
+            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/prepare_app.yml/runs" | \
+            jq -r '.workflow_runs[0].id')
+          echo "run_id=$run_id" >> $GITHUB_OUTPUT
+          echo "Current run_id: $run_id"
+
+      - name: Clone external action repository
+        run: |
+          git clone https://github.com/kamilchodola/wait-for-workflow-action.git /tmp/wait-for-workflow-action
+          ls -la /tmp/wait-for-workflow-action
+
+      - name: Make the script executable
+        run: |
+          if [ -f /tmp/wait-for-workflow-action/scripts/wait-for-workflow.sh ]; then
+            chmod +x /tmp/wait-for-workflow-action/scripts/wait-for-workflow.sh
+          else
+            echo "Error: /tmp/wait-for-workflow-action/scripts/wait-for-workflow.sh does not exist."
+            exit 1
+          fi
+
+      - name: Wait for Workflow Action
+        run: /tmp/wait-for-workflow-action/scripts/wait-for-workflow.sh
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
+          WORKFLOW_ID: "prepare_app.yml"
+          RUN_ID: ${{ steps.get_run_id.outputs.run_id }}
+          MAX_WAIT_MINUTES: "3"
+          INTERVAL: "5"
+          TIMEOUT: "10"
+          ORG_NAME: "dasteff91"
+          REPO_NAME: "website_kite-engineer"
+          REF: "${{ github.ref }}"
+
       - name: Checkout the repository code
         uses: actions/checkout@v5
         with:
